-- PopMastery: user, activity and social schema

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  display_name text,
  email text,
  avatar_url text,
  provider text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  last_login_at timestamptz
);

create table if not exists public.public_profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  username text not null unique,
  display_name text not null default 'Learner',
  avatar_url text,
  cover_url text,
  bio text not null default '',
  website text,
  location text,
  is_public boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.game_results (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  game text not null,
  score numeric,
  accuracy numeric,
  wpm numeric,
  reaction_ms integer,
  level integer,
  duration_seconds integer,
  metadata jsonb not null default '{}'::jsonb,
  played_at timestamptz not null default now()
);

create table if not exists public.activity_events (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  event_type text not null,
  game text,
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.user_interests (
  user_id uuid not null references auth.users(id) on delete cascade,
  interest text not null,
  score integer not null default 1,
  last_seen_at timestamptz not null default now(),
  primary key (user_id, interest)
);

create table if not exists public.follows (
  follower_id uuid not null references auth.users(id) on delete cascade,
  following_id uuid not null references auth.users(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (follower_id, following_id),
  check (follower_id <> following_id)
);

create table if not exists public.posts (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  content text not null default '',
  game text,
  result_id bigint references public.game_results(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (char_length(content) <= 1000)
);

create table if not exists public.post_likes (
  post_id bigint not null references public.posts(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (post_id, user_id)
);

create table if not exists public.post_comments (
  id bigint generated by default as identity primary key,
  post_id bigint not null references public.posts(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  content text not null,
  created_at timestamptz not null default now(),
  check (char_length(content) between 1 and 500)
);

create table if not exists public.post_shares (
  id bigint generated by default as identity primary key,
  post_id bigint not null references public.posts(id) on delete cascade,
  user_id uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now()
);

create table if not exists public.notifications (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  actor_id uuid references auth.users(id) on delete cascade,
  type text not null,
  post_id bigint references public.posts(id) on delete cascade,
  created_at timestamptz not null default now(),
  read_at timestamptz
);

-- Safe upgrades for an already-created database.
alter table public.profiles add column if not exists email text;
alter table public.profiles add column if not exists provider text;
alter table public.profiles add column if not exists metadata jsonb not null default '{}'::jsonb;
alter table public.profiles add column if not exists last_login_at timestamptz;

alter table public.profiles enable row level security;
alter table public.public_profiles enable row level security;
alter table public.game_results enable row level security;
alter table public.activity_events enable row level security;
alter table public.user_interests enable row level security;
alter table public.follows enable row level security;
alter table public.posts enable row level security;
alter table public.post_likes enable row level security;
alter table public.post_comments enable row level security;
alter table public.post_shares enable row level security;
alter table public.notifications enable row level security;

drop policy if exists "profiles_select_own" on public.profiles;
drop policy if exists "profiles_insert_own" on public.profiles;
drop policy if exists "profiles_update_own" on public.profiles;
drop policy if exists "public_profiles_read" on public.public_profiles;
drop policy if exists "public_profiles_insert_own" on public.public_profiles;
drop policy if exists "public_profiles_update_own" on public.public_profiles;
drop policy if exists "results_select_own" on public.game_results;
drop policy if exists "results_insert_own" on public.game_results;
drop policy if exists "events_select_own" on public.activity_events;
drop policy if exists "events_insert_own" on public.activity_events;
drop policy if exists "interests_select_own" on public.user_interests;
drop policy if exists "interests_insert_own" on public.user_interests;
drop policy if exists "interests_update_own" on public.user_interests;
drop policy if exists "follows_read" on public.follows;
drop policy if exists "follows_insert_own" on public.follows;
drop policy if exists "follows_delete_own" on public.follows;
drop policy if exists "posts_read_public" on public.posts;
drop policy if exists "posts_insert_own" on public.posts;
drop policy if exists "posts_update_own" on public.posts;
drop policy if exists "posts_delete_own" on public.posts;
drop policy if exists "likes_read" on public.post_likes;
drop policy if exists "likes_insert_own" on public.post_likes;
drop policy if exists "likes_delete_own" on public.post_likes;
drop policy if exists "comments_read" on public.post_comments;
drop policy if exists "comments_insert_own" on public.post_comments;
drop policy if exists "comments_delete_own" on public.post_comments;
drop policy if exists "shares_read" on public.post_shares;
drop policy if exists "shares_insert_own" on public.post_shares;
drop policy if exists "notifications_read_own" on public.notifications;
drop policy if exists "notifications_update_own" on public.notifications;

create policy "profiles_select_own" on public.profiles for select using (auth.uid() = id);
create policy "profiles_insert_own" on public.profiles for insert with check (auth.uid() = id);
create policy "profiles_update_own" on public.profiles for update using (auth.uid() = id) with check (auth.uid() = id);

create policy "public_profiles_read" on public.public_profiles for select using (is_public = true or auth.uid() = id);
create policy "public_profiles_insert_own" on public.public_profiles for insert with check (auth.uid() = id);
create policy "public_profiles_update_own" on public.public_profiles for update using (auth.uid() = id) with check (auth.uid() = id);

create policy "results_select_own" on public.game_results for select using (auth.uid() = user_id);
create policy "results_insert_own" on public.game_results for insert with check (auth.uid() = user_id);
create policy "events_select_own" on public.activity_events for select using (auth.uid() = user_id);
create policy "events_insert_own" on public.activity_events for insert with check (auth.uid() = user_id);
create policy "interests_select_own" on public.user_interests for select using (auth.uid() = user_id);
create policy "interests_insert_own" on public.user_interests for insert with check (auth.uid() = user_id);
create policy "interests_update_own" on public.user_interests for update using (auth.uid() = user_id) with check (auth.uid() = user_id);

create policy "follows_read" on public.follows for select using (true);
create policy "follows_insert_own" on public.follows for insert with check (auth.uid() = follower_id);
create policy "follows_delete_own" on public.follows for delete using (auth.uid() = follower_id);

create policy "posts_read_public" on public.posts for select using (
  exists (select 1 from public.public_profiles p where p.id = posts.user_id and p.is_public = true)
  or auth.uid() = user_id
);
create policy "posts_insert_own" on public.posts for insert with check (auth.uid() = user_id);
create policy "posts_update_own" on public.posts for update using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "posts_delete_own" on public.posts for delete using (auth.uid() = user_id);

create policy "likes_read" on public.post_likes for select using (true);
create policy "likes_insert_own" on public.post_likes for insert with check (auth.uid() = user_id);
create policy "likes_delete_own" on public.post_likes for delete using (auth.uid() = user_id);
create policy "comments_read" on public.post_comments for select using (true);
create policy "comments_insert_own" on public.post_comments for insert with check (auth.uid() = user_id);
create policy "comments_delete_own" on public.post_comments for delete using (auth.uid() = user_id);
create policy "shares_read" on public.post_shares for select using (true);
create policy "shares_insert_own" on public.post_shares for insert with check (auth.uid() = user_id or user_id is null);
create policy "notifications_read_own" on public.notifications for select using (auth.uid() = user_id);
create policy "notifications_update_own" on public.notifications for update using (auth.uid() = user_id) with check (auth.uid() = user_id);

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = public
as $$
declare
  base_username text;
  final_username text;
begin
  base_username := lower(regexp_replace(coalesce(new.raw_user_meta_data->>'user_name', new.raw_user_meta_data->>'preferred_username', new.raw_user_meta_data->>'name', split_part(coalesce(new.email, ''), '@', 1), 'learner'), '[^a-zA-Z0-9_]+', '-', 'g'));
  base_username := trim(both '-' from base_username);
  if base_username = '' then base_username := 'learner'; end if;
  final_username := left(base_username, 28) || '-' || substr(replace(new.id::text, '-', ''), 1, 8);

  insert into public.profiles (id, display_name, email, avatar_url, provider, metadata, last_login_at)
  values (
    new.id,
    coalesce(new.raw_user_meta_data->>'display_name', new.raw_user_meta_data->>'full_name', new.raw_user_meta_data->>'name', split_part(coalesce(new.email, ''), '@', 1), 'Learner'),
    new.email,
    coalesce(new.raw_user_meta_data->>'avatar_url', new.raw_user_meta_data->>'picture'),
    coalesce(new.raw_app_meta_data->>'provider', 'email'),
    coalesce(new.raw_user_meta_data, '{}'::jsonb),
    now()
  ) on conflict (id) do nothing;

  insert into public.public_profiles (id, username, display_name, avatar_url)
  values (
    new.id,
    final_username,
    coalesce(new.raw_user_meta_data->>'display_name', new.raw_user_meta_data->>'full_name', new.raw_user_meta_data->>'name', split_part(coalesce(new.email, ''), '@', 1), 'Learner'),
    coalesce(new.raw_user_meta_data->>'avatar_url', new.raw_user_meta_data->>'picture')
  ) on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created after insert on auth.users for each row execute procedure public.handle_new_user();

create or replace function public.notify_follow()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  insert into public.notifications(user_id, actor_id, type) values (new.following_id, new.follower_id, 'follow');
  return new;
end; $$;

drop trigger if exists on_follow_created on public.follows;
create trigger on_follow_created after insert on public.follows for each row execute procedure public.notify_follow();

create index if not exists game_results_user_played_idx on public.game_results(user_id, played_at desc);
create index if not exists activity_events_user_created_idx on public.activity_events(user_id, created_at desc);
create index if not exists user_interests_user_score_idx on public.user_interests(user_id, score desc);
create index if not exists follows_following_idx on public.follows(following_id, created_at desc);
create index if not exists follows_follower_idx on public.follows(follower_id, created_at desc);
create index if not exists posts_user_created_idx on public.posts(user_id, created_at desc);
create index if not exists posts_created_idx on public.posts(created_at desc);
create index if not exists post_likes_post_idx on public.post_likes(post_id);
create index if not exists post_comments_post_idx on public.post_comments(post_id, created_at desc);
create index if not exists notifications_user_idx on public.notifications(user_id, created_at desc);
