-- PopMastery: complete user/profile/activity schema

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  display_name text,
  email text,
  avatar_url text,
  provider text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  last_login_at timestamptz
);

create table if not exists public.game_results (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  game text not null,
  score numeric,
  accuracy numeric,
  wpm numeric,
  reaction_ms integer,
  level integer,
  duration_seconds integer,
  metadata jsonb not null default '{}'::jsonb,
  played_at timestamptz not null default now()
);

create table if not exists public.activity_events (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  event_type text not null,
  game text,
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.user_interests (
  user_id uuid not null references auth.users(id) on delete cascade,
  interest text not null,
  score integer not null default 1,
  last_seen_at timestamptz not null default now(),
  primary key (user_id, interest)
);

-- Safe upgrades for an already-created database.
alter table public.profiles add column if not exists email text;
alter table public.profiles add column if not exists provider text;
alter table public.profiles add column if not exists metadata jsonb not null default '{}'::jsonb;
alter table public.profiles add column if not exists last_login_at timestamptz;

alter table public.profiles enable row level security;
alter table public.game_results enable row level security;
alter table public.activity_events enable row level security;
alter table public.user_interests enable row level security;

drop policy if exists "profiles_select_own" on public.profiles;
drop policy if exists "profiles_insert_own" on public.profiles;
drop policy if exists "profiles_update_own" on public.profiles;
drop policy if exists "results_select_own" on public.game_results;
drop policy if exists "results_insert_own" on public.game_results;
drop policy if exists "events_select_own" on public.activity_events;
drop policy if exists "events_insert_own" on public.activity_events;
drop policy if exists "interests_select_own" on public.user_interests;
drop policy if exists "interests_insert_own" on public.user_interests;
drop policy if exists "interests_update_own" on public.user_interests;

create policy "profiles_select_own" on public.profiles for select using (auth.uid() = id);
create policy "profiles_insert_own" on public.profiles for insert with check (auth.uid() = id);
create policy "profiles_update_own" on public.profiles for update using (auth.uid() = id) with check (auth.uid() = id);

create policy "results_select_own" on public.game_results for select using (auth.uid() = user_id);
create policy "results_insert_own" on public.game_results for insert with check (auth.uid() = user_id);

create policy "events_select_own" on public.activity_events for select using (auth.uid() = user_id);
create policy "events_insert_own" on public.activity_events for insert with check (auth.uid() = user_id);

create policy "interests_select_own" on public.user_interests for select using (auth.uid() = user_id);
create policy "interests_insert_own" on public.user_interests for insert with check (auth.uid() = user_id);
create policy "interests_update_own" on public.user_interests for update using (auth.uid() = user_id) with check (auth.uid() = user_id);

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
  insert into public.profiles (id, display_name, email, avatar_url, provider, metadata, last_login_at)
  values (
    new.id,
    coalesce(new.raw_user_meta_data->>'display_name', new.raw_user_meta_data->>'full_name', split_part(coalesce(new.email, ''), '@', 1), 'Learner'),
    new.email,
    coalesce(new.raw_user_meta_data->>'avatar_url', new.raw_user_meta_data->>'picture'),
    coalesce(new.raw_app_meta_data->>'provider', 'email'),
    coalesce(new.raw_user_meta_data, '{}'::jsonb),
    now()
  )
  on conflict (id) do update set
    email = excluded.email,
    avatar_url = coalesce(excluded.avatar_url, public.profiles.avatar_url),
    provider = excluded.provider,
    metadata = excluded.metadata,
    updated_at = now(),
    last_login_at = now();
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute procedure public.handle_new_user();

create index if not exists game_results_user_played_idx on public.game_results(user_id, played_at desc);
create index if not exists activity_events_user_created_idx on public.activity_events(user_id, created_at desc);
create index if not exists user_interests_user_score_idx on public.user_interests(user_id, score desc);
