-- PopMastery social migration
-- Run this AFTER the original supabase schema.sql.
-- Safe to run more than once.

-- Extend the existing private profile table without replacing it.
alter table public.profiles add column if not exists username text;
alter table public.profiles add column if not exists bio text;
alter table public.profiles add column if not exists location text;
alter table public.profiles add column if not exists website text;
alter table public.profiles add column if not exists cover_url text;

-- Public-facing profile data. Keep this separate from private account data.
create table if not exists public.public_profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  username text not null unique,
  display_name text not null default 'Learner',
  avatar_url text,
  cover_url text,
  bio text,
  location text,
  website text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.follows (
  follower_id uuid not null references auth.users(id) on delete cascade,
  following_id uuid not null references auth.users(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (follower_id, following_id),
  check (follower_id <> following_id)
);

create table if not exists public.posts (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  content text not null check (char_length(content) between 1 and 2000),
  game text,
  result_id bigint references public.game_results(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.post_likes (
  post_id bigint not null references public.posts(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (post_id, user_id)
);

create table if not exists public.post_comments (
  id bigint generated by default as identity primary key,
  post_id bigint not null references public.posts(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  content text not null check (char_length(content) between 1 and 1000),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.post_shares (
  id bigint generated by default as identity primary key,
  post_id bigint not null references public.posts(id) on delete cascade,
  user_id uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now()
);

create table if not exists public.notifications (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  actor_id uuid references auth.users(id) on delete set null,
  type text not null,
  post_id bigint references public.posts(id) on delete cascade,
  read_at timestamptz,
  created_at timestamptz not null default now()
);

-- Helpful indexes.
create index if not exists public_profiles_username_idx on public.public_profiles(username);
create index if not exists follows_following_idx on public.follows(following_id, created_at desc);
create index if not exists follows_follower_idx on public.follows(follower_id, created_at desc);
create index if not exists posts_user_created_idx on public.posts(user_id, created_at desc);
create index if not exists posts_created_idx on public.posts(created_at desc);
create index if not exists post_comments_post_idx on public.post_comments(post_id, created_at asc);
create index if not exists notifications_user_created_idx on public.notifications(user_id, created_at desc);

-- Enable RLS.
alter table public.public_profiles enable row level security;
alter table public.follows enable row level security;
alter table public.posts enable row level security;
alter table public.post_likes enable row level security;
alter table public.post_comments enable row level security;
alter table public.post_shares enable row level security;
alter table public.notifications enable row level security;

-- Public profiles are public; owners can create/update their own profile.
drop policy if exists "public_profiles_select_public" on public.public_profiles;
drop policy if exists "public_profiles_insert_own" on public.public_profiles;
drop policy if exists "public_profiles_update_own" on public.public_profiles;
create policy "public_profiles_select_public" on public.public_profiles for select using (true);
create policy "public_profiles_insert_own" on public.public_profiles for insert with check (auth.uid() = id);
create policy "public_profiles_update_own" on public.public_profiles for update using (auth.uid() = id) with check (auth.uid() = id);

-- Follows are public for counts/lists; only the logged-in user can create/remove their own follows.
drop policy if exists "follows_select_public" on public.follows;
drop policy if exists "follows_insert_own" on public.follows;
drop policy if exists "follows_delete_own" on public.follows;
create policy "follows_select_public" on public.follows for select using (true);
create policy "follows_insert_own" on public.follows for insert with check (auth.uid() = follower_id);
create policy "follows_delete_own" on public.follows for delete using (auth.uid() = follower_id);

-- Posts are public; authenticated users can publish/edit/delete only their own.
drop policy if exists "posts_select_public" on public.posts;
drop policy if exists "posts_insert_auth" on public.posts;
drop policy if exists "posts_update_own" on public.posts;
drop policy if exists "posts_delete_own" on public.posts;
create policy "posts_select_public" on public.posts for select using (true);
create policy "posts_insert_auth" on public.posts for insert to authenticated with check (auth.uid() = user_id);
create policy "posts_update_own" on public.posts for update using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "posts_delete_own" on public.posts for delete using (auth.uid() = user_id);

-- Likes are public; users control their own likes.
drop policy if exists "post_likes_select_public" on public.post_likes;
drop policy if exists "post_likes_insert_own" on public.post_likes;
drop policy if exists "post_likes_delete_own" on public.post_likes;
create policy "post_likes_select_public" on public.post_likes for select using (true);
create policy "post_likes_insert_own" on public.post_likes for insert to authenticated with check (auth.uid() = user_id);
create policy "post_likes_delete_own" on public.post_likes for delete to authenticated using (auth.uid() = user_id);

-- Comments are public; authenticated users control their own comments.
drop policy if exists "post_comments_select_public" on public.post_comments;
drop policy if exists "post_comments_insert_own" on public.post_comments;
drop policy if exists "post_comments_update_own" on public.post_comments;
drop policy if exists "post_comments_delete_own" on public.post_comments;
create policy "post_comments_select_public" on public.post_comments for select using (true);
create policy "post_comments_insert_own" on public.post_comments for insert to authenticated with check (auth.uid() = user_id);
create policy "post_comments_update_own" on public.post_comments for update using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "post_comments_delete_own" on public.post_comments for delete using (auth.uid() = user_id);

-- Shares are public; authenticated users can record their own shares.
drop policy if exists "post_shares_select_public" on public.post_shares;
drop policy if exists "post_shares_insert_auth" on public.post_shares;
create policy "post_shares_select_public" on public.post_shares for select using (true);
create policy "post_shares_insert_auth" on public.post_shares for insert to authenticated with check (auth.uid() = user_id);

-- Notifications are private to their recipient.
drop policy if exists "notifications_select_own" on public.notifications;
drop policy if exists "notifications_update_own" on public.notifications;
create policy "notifications_select_own" on public.notifications for select using (auth.uid() = user_id);
create policy "notifications_update_own" on public.notifications for update using (auth.uid() = user_id) with check (auth.uid() = user_id);

-- Keep a public profile in sync for users who already exist and future users.
insert into public.public_profiles (id, username, display_name, avatar_url)
select p.id,
       lower(regexp_replace(coalesce(nullif(p.display_name, ''), 'learner'), '[^a-zA-Z0-9_]+', '-', 'g')) || '-' || substr(p.id::text, 1, 6),
       coalesce(nullif(p.display_name, ''), 'Learner'),
       p.avatar_url
from public.profiles p
on conflict (id) do nothing;

create or replace function public.handle_new_social_profile()
returns trigger
language plpgsql
security definer set search_path = public
as $$
declare
  base_username text;
begin
  base_username := lower(regexp_replace(coalesce(nullif(new.raw_user_meta_data->>'display_name', ''), split_part(coalesce(new.email, ''), '@', 1), 'learner'), '[^a-zA-Z0-9_]+', '-', 'g'));
  if base_username = '' then base_username := 'learner'; end if;
  insert into public.public_profiles (id, username, display_name, avatar_url)
  values (new.id, base_username || '-' || substr(new.id::text, 1, 6), coalesce(new.raw_user_meta_data->>'display_name', split_part(coalesce(new.email, ''), '@', 1), 'Learner'), new.raw_user_meta_data->>'avatar_url')
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_social_profile_created on auth.users;
create trigger on_auth_social_profile_created
after insert on auth.users
for each row execute procedure public.handle_new_social_profile();
