// PopMastery game engine + Supabase activity tracking.
const modal=document.getElementById('modal'),gameArea=document.getElementById('gameArea'),modalTitle=document.getElementById('modalTitle'),modalText=document.getElementById('modalText');
const authModal=document.getElementById('authModal'),authForm=document.getElementById('authForm'),authTitle=document.getElementById('authTitle'),authText=document.getElementById('authText'),authSubmit=document.getElementById('authSubmit'),switchAuth=document.getElementById('switchAuth'),authMessage=document.getElementById('authMessage');
let authMode='signup';
const openModal=()=>{modal.classList.add('open');modal.setAttribute('aria-hidden','false')};
const closeModal=()=>{modal.classList.remove('open');modal.setAttribute('aria-hidden','true')};
document.getElementById('closeModal').onclick=closeModal;modal.addEventListener('click',e=>{if(e.target===modal)closeModal()});

document.querySelectorAll('[data-game]').forEach(card=>card.addEventListener('click',()=>launch(card.dataset.game)));
['heroPlay','quickPlay','ctaPlay'].forEach(id=>document.getElementById(id).addEventListener('click',()=>launch('typing')));
document.getElementById('reactionBtn').addEventListener('click',()=>launch('focus'));
document.getElementById('profileBtn').onclick=()=>window.popUser?openProfile():openAuth();
document.getElementById('authBtn').onclick=()=>window.popUser?openProfile():openAuth();
document.getElementById('closeProfile').onclick=closeProfile;document.getElementById('signOut').onclick=async()=>{await window.popSignOut?.();closeProfile()};
switchAuth.onclick=e=>{e.preventDefault();authMode=authMode==='signup'?'signin':'signup';renderAuth()};document.getElementById('closeAuth').onclick=()=>{authModal.classList.remove('open');authModal.setAttribute('aria-hidden','true')};authModal.addEventListener('click',e=>{if(e.target===authModal)document.getElementById('closeAuth').click()});authForm.onsubmit=handleAuth;

function openAuth(){authForm.style.display='block';switchAuth.style.display='block';renderAuth();authModal.classList.add('open');authModal.setAttribute('aria-hidden','false')}
function renderAuth(){document.getElementById('authName').style.display=authMode==='signin'?'none':'block';authTitle.textContent=authMode==='signin'?'Welcome back':'Save your progress';authText.textContent=authMode==='signin'?'Sign in to continue your progress.':'Create a free account to keep every result and build your personal learning profile.';authSubmit.textContent=authMode==='signin'?'Sign in':'Create account';switchAuth.textContent=authMode==='signin'?'New here? Create a free account':'Already have an account? Sign in';authMessage.textContent=''}
async function handleAuth(e){e.preventDefault();if(!window.popSupabase){authMessage.textContent='Supabase is not configured yet. Add the project URL and anon/publishable key in supabase-config.js.';return}authMessage.textContent='Working…';const email=document.getElementById('authEmail').value.trim(),password=document.getElementById('authPassword').value,name=document.getElementById('authName').value.trim();const r=authMode==='signin'?await window.popSignIn(email,password):await window.popSignUp(name,email,password);if(r.error){authMessage.textContent=r.error.message;return}if(authMode==='signup'&&!r.data.session){authMessage.textContent='Account created. Check your email to confirm, then sign in.'}else{authMessage.textContent='Success!';setTimeout(()=>document.getElementById('closeAuth').click(),500)}}
function openProfile(){loadProfile().then(()=>{document.getElementById('profileDrawer').classList.add('open');document.getElementById('profileDrawer').setAttribute('aria-hidden','false')})}
function closeProfile(){document.getElementById('profileDrawer').classList.remove('open');document.getElementById('profileDrawer').setAttribute('aria-hidden','true')}
function launch(type){openModal();({typing,memory,math,focus}[type]||typing)()}

async function saveResult(game,result){if(window.popSaveResult&&window.popUser){await window.popSaveResult(game,result);loadProfile()}}
function typing(){modalTitle.textContent='Typing Rush';modalText.textContent='Type the sentence as quickly and accurately as you can.';const target='Small steps every day create big skills.';gameArea.innerHTML=`<div class="type-text">${target}</div><input class="type-input" id="typeInput" autocomplete="off" placeholder="Start typing here…"><div class="type-result" id="typeResult">0 characters typed</div>`;const input=document.getElementById('typeInput'),result=document.getElementById('typeResult'),start=performance.now();input.focus();input.oninput=()=>{const v=input.value;let correct=0;for(let i=0;i<Math.min(v.length,target.length);i++)if(v[i]===target[i])correct++;const minutes=Math.max(.001,(performance.now()-start)/60000),wpm=Math.round((correct/5)/minutes),accuracy=v.length?Math.round(correct/v.length*100):0;result.textContent=`${correct}/${target.length} correct • ${wpm} WPM • ${accuracy}% accuracy`;if(v===target){saveResult('typing',{score:wpm,accuracy,wpm,duration_seconds:Math.round((performance.now()-start)/1000),metadata:{text_length:target.length}});result.textContent=`Complete! ${wpm} WPM • ${accuracy}% accuracy 🎉`}}}
function memory(){modalTitle.textContent='Memory Flip';modalText.textContent='Find the matching pairs. Take your time — accuracy first.';const symbols=['◆','◆','●','●','▲','▲','★','★'];symbols.sort(()=>Math.random()-.5);gameArea.innerHTML='<div class="memory-grid">'+symbols.map((s,i)=>`<button class="memory-card" data-s="${s}">${s}</button>`).join('')+'</div><div class="type-result" id="memResult">0 pairs found</div>';let open=[],pairs=0,moves=0,locked=false;const cards=[...gameArea.querySelectorAll('.memory-card')];cards.forEach(c=>c.onclick=()=>{if(locked||c.classList.contains('flipped'))return;c.classList.add('flipped');open.push(c);moves++;if(open.length===2){locked=true;if(open[0].dataset.s===open[1].dataset.s){pairs++;open=[];locked=false;document.getElementById('memResult').textContent=`${pairs}/4 pairs found`;if(pairs===4){const score=Math.max(100,500-moves*25);document.getElementById('memResult').textContent=`Perfect! ${score} points 🧠`;saveResult('memory',{score,accuracy:Math.round(8/moves*100),level:4,metadata:{moves}})}}else setTimeout(()=>{open.forEach(x=>x.classList.remove('flipped'));open=[];locked=false},550)}})}
function math(){modalTitle.textContent='Math Sprint';modalText.textContent='Choose the correct answer. New question every round.';let score=0;nextMath() ;function nextMath(){const a=Math.floor(Math.random()*20)+5,b=Math.floor(Math.random()*15)+2,ans=a+b;const options=[ans,ans+2,ans-3,ans+5].sort(()=>Math.random()-.5);gameArea.innerHTML=`<div class="math-q">${a} + ${b} = ?</div><div class="choices">${options.map(x=>`<button class="choice" data-a="${x}">${x}</button>`).join('')}</div><div class="type-result">Score: ${score}</div>`;gameArea.querySelectorAll('.choice').forEach(x=>x.onclick=()=>{if(+x.dataset.a===ans){score++;saveResult('math',{score,level:score,metadata:{correct:score}});setTimeout(nextMath,450)}else x.textContent='Try again'}})}}
function focus(){modalTitle.textContent='Focus Hunt';modalText.textContent='Click the target as soon as it appears. Beat your reaction time.';gameArea.innerHTML='<div class="focus-board" id="focusBoard"></div><div class="focus-score" id="focusScore">Get ready…</div>';const board=document.getElementById('focusBoard'),score=document.getElementById('focusScore');function spawn(){board.innerHTML='<button class="focus-dot" aria-label="target"></button>';const dot=board.firstChild;dot.style.left=(Math.random()*84+6)+'%';dot.style.top=(Math.random()*78+8)+'%';const start=performance.now();dot.onclick=()=>{const ms=Math.round(performance.now()-start);score.textContent=`${ms} ms — ${ms<300?'Lightning fast! 🔥':'Nice! Try to beat it.'}`;saveResult('focus',{score:Math.max(1,1000-ms),reaction_ms:ms,metadata:{fast:ms<300}});setTimeout(spawn,650)}}setTimeout(spawn,700)}

async function loadProfile(){const d=await window.popGetProfile?.();if(!d)return;const name=d.profile?.display_name||window.popUser?.user_metadata?.display_name||window.popUser?.email?.split('@')[0]||'Learner';document.getElementById('profileName').textContent=name;document.getElementById('profileEmail').textContent=window.popUser?.email||'—';document.getElementById('avatar').textContent=name[0].toUpperCase();document.getElementById('totalPlays').textContent=d.results.length;document.getElementById('bestScore').textContent=Math.round(Math.max(0,...d.results.map(r=>Number(r.score)||0)));document.getElementById('streak').textContent=new Set(d.results.map(r=>new Date(r.played_at).toISOString().slice(0,10))).size;const scores={typing:0,memory:0,math:0,focus:0};d.results.forEach(r=>{if(r.game==='typing')scores.typing=Math.max(scores.typing,Math.min(100,Number(r.accuracy)||0));if(r.game==='memory')scores.memory=Math.max(scores.memory,Math.min(100,Number(r.accuracy)||0));if(r.game==='math')scores.math=Math.max(scores.math,Math.min(100,Number(r.score)||0)*10);if(r.game==='focus')scores.focus=Math.max(scores.focus,Math.min(100,Number(r.score)||0)/10)});Object.entries(scores).forEach(([k,v])=>{document.getElementById(k+'Bar').style.width=Math.round(v)+'%';document.getElementById(k+'Score').textContent=Math.round(v)||'—'});document.getElementById('trend').textContent=`${d.results.length} recorded result${d.results.length===1?'':'s'} — keep playing to grow your skill map.`;document.getElementById('activityList').innerHTML=d.activities.length?d.activities.slice(0,10).map(e=>`<div class="activity-item"><b>${e.game||e.event_type}</b><span>${new Date(e.created_at).toLocaleString()}</span></div>`).join(''):'<p class="muted">No activity yet.</p>';document.getElementById('interestList').innerHTML=d.interests.length?d.interests.map(i=>`<span class="interest-pill">${i.interest} · ${i.score}</span>`).join(''):'<span class="muted">Play games to discover your interests.</span>'}

function updateAuthUI(){const b=document.getElementById('authBtn');b.textContent=window.popUser?(window.popUser.user_metadata?.display_name||window.popUser.email?.split('@')[0]||'Profile'):'Sign in'}
window.addEventListener('pop-auth-ready',()=>{updateAuthUI();if(window.popUser)loadProfile()});updateAuthUI();
