const modal=document.getElementById('modal'),gameArea=document.getElementById('gameArea'),modalTitle=document.getElementById('modalTitle'),modalText=document.getElementById('modalText');
const openModal=()=>{modal.classList.add('open');modal.setAttribute('aria-hidden','false')};
const closeModal=()=>{modal.classList.remove('open');modal.setAttribute('aria-hidden','true')};
document.getElementById('closeModal').onclick=closeModal;
modal.addEventListener('click',e=>{if(e.target===modal)closeModal()});

document.querySelectorAll('[data-game]').forEach(card=>card.addEventListener('click',()=>launch(card.dataset.game)));
['heroPlay','quickPlay','ctaPlay'].forEach(id=>document.getElementById(id).addEventListener('click',()=>launch('typing')));

document.getElementById('reactionBtn').addEventListener('click',()=>launch('focus'));

document.getElementById('demoProgress').addEventListener('click',()=>{document.querySelector('.skill-panel').scrollIntoView({behavior:'smooth',block:'center'});});

function launch(type){openModal();if(type==='typing')typing();if(type==='memory')memory();if(type==='math')math();if(type==='focus')focus();}
function typing(){modalTitle.textContent='Typing Rush';modalText.textContent='Type the sentence as quickly and accurately as you can.';gameArea.innerHTML='<div class="type-text">Small steps every day create big skills.</div><input class="type-input" id="typeInput" autocomplete="off" placeholder="Start typing here…"><div class="type-result" id="typeResult">0 characters typed</div>';const input=document.getElementById('typeInput'),result=document.getElementById('typeResult'),start=performance.now();input.focus();input.addEventListener('input',()=>{const target='Small steps every day create big skills.';const v=input.value;let correct=0;for(let i=0;i<Math.min(v.length,target.length);i++)if(v[i]===target[i])correct++;const elapsed=Math.max(1,(performance.now()-start)/60000);const wpm=Math.round((correct/5)/elapsed);result.textContent=`${correct}/${target.length} correct • ${wpm} WPM`});}
function memory(){modalTitle.textContent='Memory Flip';modalText.textContent='Find the matching pairs. Take your time — accuracy first.';const symbols=['◆','◆','●','●','▲','▲','★','★'];symbols.sort(()=>Math.random()-.5);gameArea.innerHTML='<div class="memory-grid">'+symbols.map((s,i)=>`<button class="memory-card" data-i="${i}" data-s="${s}">${s}</button>`).join('')+'</div><div class="type-result" id="memResult">0 pairs found</div>';let open=[],pairs=0,locked=false;const cards=[...gameArea.querySelectorAll('.memory-card')];cards.forEach(c=>c.onclick=()=>{if(locked||c.classList.contains('flipped'))return;c.classList.add('flipped');open.push(c);if(open.length===2){locked=true;if(open[0].dataset.s===open[1].dataset.s){pairs++;open=[];locked=false;document.getElementById('memResult').textContent=`${pairs}/4 pairs found`;if(pairs===4)document.getElementById('memResult').textContent='Perfect! Memory master 🧠';}else setTimeout(()=>{open.forEach(x=>x.classList.remove('flipped'));open=[];locked=false},550)}})}
function math(){modalTitle.textContent='Math Sprint';modalText.textContent='Choose the correct answer. New question every round.';newMath();}
function newMath(){const a=Math.floor(Math.random()*20)+5,b=Math.floor(Math.random()*15)+2,ans=a+b;const options=[ans,ans+2,ans-3,ans+5].sort(()=>Math.random()-.5);gameArea.innerHTML=`<div class="math-q">${a} + ${b} = ?</div><div class="choices">${options.map(x=>`<button class="choice" data-a="${x}">${x}</button>`).join('')}</div><div class="type-result" id="mathResult">Get it right to continue.</div>`;gameArea.querySelectorAll('.choice').forEach(x=>x.onclick=()=>{const r=document.getElementById('mathResult');if(+x.dataset.a===ans){r.textContent='Correct! ⚡';setTimeout(newMath,450)}else r.textContent='Not quite — try again.'})}
function focus(){modalTitle.textContent='Focus Hunt';modalText.textContent='Click the target as soon as it appears. Beat your reaction time.';gameArea.innerHTML='<div class="focus-board" id="focusBoard"></div><div class="focus-score" id="focusScore">Get ready…</div>';const board=document.getElementById('focusBoard'),score=document.getElementById('focusScore');let start;function spawn(){board.innerHTML='<button class="focus-dot" aria-label="target"></button>';const dot=board.firstChild;dot.style.left=(Math.random()*84+6)+'%';dot.style.top=(Math.random()*78+8)+'%';start=performance.now();dot.onclick=()=>{const ms=Math.round(performance.now()-start);score.textContent=`${ms} ms — ${ms<300?'Lightning fast! 🔥':'Nice! Try to beat it.'}`;setTimeout(spawn,650)}}setTimeout(spawn,700)}
