/* PopMastery authentication + Supabase profile/social sync. */
(function () {
  const configured = Boolean(window.supabase && window.POPMASTERY_SUPABASE_URL && window.POPMASTERY_SUPABASE_ANON_KEY && !window.POPMASTERY_SUPABASE_URL.includes('YOUR_') && !window.POPMASTERY_SUPABASE_ANON_KEY.includes('YOUR_'));
  const POP = configured ? window.supabase.createClient(window.POPMASTERY_SUPABASE_URL, window.POPMASTERY_SUPABASE_ANON_KEY, { auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true} }) : null;
  window.popSupabase=POP; window.popUser=null; let lastSyncedUserId=null;
  const redirect=()=> 'https://popmastery.pages.dev/';
  function usernameFor(user){const m=user.user_metadata||{},raw=m.user_name||m.preferred_username||m.name||user.email?.split('@')[0]||'learner';const clean=raw.toLowerCase().replace(/[^a-z0-9_]+/g,'-').replace(/^-+|-+$/g,'').slice(0,28)||'learner';return `${clean}-${user.id.replaceAll('-','').slice(0,8)}`;}
  async function syncProfile(user,eventType){
    if(!POP||!user)return; const m=user.user_metadata||{},displayName=m.display_name||m.full_name||m.name||user.email?.split('@')[0]||'Learner',avatarUrl=m.avatar_url||m.picture||null,provider=user.app_metadata?.provider||'email',now=new Date().toISOString();
    const {error:profileError}=await POP.from('profiles').upsert({id:user.id,display_name:displayName,email:user.email||null,avatar_url:avatarUrl,provider,metadata:m,updated_at:now,...(eventType==='SIGNED_IN'?{last_login_at:now}:{})},{onConflict:'id'}); if(profileError)console.warn('Profile sync failed:',profileError.message);
    const {error:publicError}=await POP.from('public_profiles').upsert({id:user.id,username:usernameFor(user),display_name:displayName,avatar_url:avatarUrl,updated_at:now},{onConflict:'id'}); if(publicError)console.warn('Public profile sync failed:',publicError.message);
    if(eventType&&eventType!=='INITIAL_SESSION'&&user.id!==lastSyncedUserId){const {error}=await POP.from('activity_events').insert({user_id:user.id,event_type:eventType==='SIGNED_IN'?'login':eventType.toLowerCase(),payload:{provider,email:user.email||null}});if(error)console.warn('Activity save failed:',error.message);lastSyncedUserId=user.id;}
  }
  async function consumeOAuthHash(){if(!POP||!location.hash.includes('access_token='))return;const hash=new URLSearchParams(location.hash.slice(1)),accessToken=hash.get('access_token'),refreshToken=hash.get('refresh_token');if(accessToken&&refreshToken){const {error}=await POP.auth.setSession({access_token:accessToken,refresh_token:refreshToken});if(error)console.warn('OAuth session restore failed:',error.message);history.replaceState({},document.title,location.pathname+location.search);}}
  window.popGoogleSignIn=async()=>{if(!POP)throw new Error('Supabase is not configured.');const {data,error}=await POP.auth.signInWithOAuth({provider:'google',options:{redirectTo:redirect()}});if(error)throw error;return data;};
  window.popSignUp=(name,email,password)=>POP.auth.signUp({email,password,options:{emailRedirectTo:redirect(),data:{display_name:name||email.split('@')[0]}}});
  window.popSignIn=(email,password)=>POP.auth.signInWithPassword({email,password});
  window.popSignOut=async()=>{if(!POP)return;if(window.popUser)await POP.from('activity_events').insert({user_id:window.popUser.id,event_type:'logout',payload:{}});return POP.auth.signOut();};
  window.popSaveActivity=async(eventType,game,payload={})=>{if(!POP||!window.popUser)return;const {error}=await POP.from('activity_events').insert({user_id:window.popUser.id,event_type,game:game||null,payload});if(error)console.warn('Activity save failed:',error.message);};
  window.popSaveResult=async(game,result={})=>{if(!POP||!window.popUser)return;const userId=window.popUser.id,row={user_id:userId,game,score:result.score??null,accuracy:result.accuracy??null,wpm:result.wpm??null,reaction_ms:result.reaction_ms??null,level:result.level??null,duration_seconds:result.duration_seconds??null,metadata:result.metadata||{}};const {data,error}=await POP.from('game_results').insert(row).select('id').single();if(error)console.warn('Result save failed:',error.message);await POP.from('activity_events').insert({user_id:userId,event_type:'game_completed',game,payload:result});const {data:interest}=await POP.from('user_interests').select('score').eq('user_id',userId).eq('interest',game).maybeSingle();await POP.from('user_interests').upsert({user_id:userId,interest:game,score:(interest?.score||0)+1,last_seen_at:new Date().toISOString()},{onConflict:'user_id,interest'});return data?.id||null;};
  window.popGetProfile=async()=>{if(!POP||!window.popUser)return null;const id=window.popUser.id;const [profile,results,activities,interests]=await Promise.all([POP.from('profiles').select('*').eq('id',id).maybeSingle(),POP.from('game_results').select('*').eq('user_id',id).order('played_at',{ascending:false}).limit(200),POP.from('activity_events').select('*').eq('user_id',id).order('created_at',{ascending:false}).limit(100),POP.from('user_interests').select('*').eq('user_id',id).order('score',{ascending:false})]);return{profile:profile.data,results:results.data||[],activities:activities.data||[],interests:interests.data||[]};};
  window.popEnsureSocialProfile=async()=>{if(!POP||!window.popUser)return null;const u=window.popUser,m=u.user_metadata||{},now=new Date().toISOString(),displayName=m.display_name||m.full_name||m.name||u.email?.split('@')[0]||'Learner';const {data:existing}=await POP.from('public_profiles').select('*').eq('id',u.id).maybeSingle();if(existing)return existing;const {data,error}=await POP.from('public_profiles').insert({id:u.id,username:usernameFor(u),display_name:displayName,avatar_url:m.avatar_url||m.picture||null,updated_at:now}).select('*').single();if(error)console.warn('Social profile create failed:',error.message);return data||null;};
  async function init(){if(!POP){window.dispatchEvent(new CustomEvent('pop-auth-ready',{detail:{user:null,configured:false}}));return;}await consumeOAuthHash();const {data,error}=await POP.auth.getSession();if(error)console.warn('Session read failed:',error.message);window.popUser=data.session?.user||null;if(window.popUser)await syncProfile(window.popUser,'INITIAL_SESSION');window.dispatchEvent(new CustomEvent('pop-auth-ready',{detail:{user:window.popUser,configured:true}}));POP.auth.onAuthStateChange(async(event,session)=>{window.popUser=session?.user||null;if(window.popUser)await syncProfile(window.popUser,event);window.dispatchEvent(new CustomEvent('pop-auth-ready',{detail:{user:window.popUser,event,configured:true}}));});}
  window.popAuthInit=init;if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();
