/* Public profile page */
(function(){
const $=id=>document.getElementById(id), P=()=>window.popSupabase;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
let target=null;
const avatar=p=>p?.avatar_url?`<img class="profile-avatar-img" src="${esc(p.avatar_url)}" alt="">`:`<span class="profile-avatar-letter">${esc((p?.display_name||'L').charAt(0).toUpperCase())}</span>`;
const pu=p=>`profile.html?u=${encodeURIComponent(p?.username||'')}`;
async function waitAuth(){
  if(window.popSupabase && window.popUser)return;
  await new Promise(resolve=>{
    const done=()=>{document.removeEventListener('pop-auth-ready',done);resolve();};
    document.addEventListener('pop-auth-ready',done,{once:true});
    setTimeout(done,5000);
  });
}
async function profiles(ids){if(!ids.length)return{};const {data}=await P().from('public_profiles').select('id,username,display_name,avatar_url,bio').in('id',[...new Set(ids)]);return Object.fromEntries((data||[]).map(x=>[x.id,x]));}
async function posts(box,rows){if(!rows?.length){box.innerHTML='<div class="empty-card"><b>No posts yet</b><span>Share a win from your next game.</span></div>';return;}const ps=await profiles(rows.map(x=>x.user_id));const ids=rows.map(x=>x.id);const {data:likes}=await P().from('post_likes').select('post_id,user_id').in('post_id',ids);const lm={};(likes||[]).forEach(x=>{lm[x.post_id]??={n:0,yes:false};lm[x.post_id].n++;lm[x.post_id].yes=x.user_id===window.popUser?.id;});box.innerHTML=rows.map(x=>{const u=ps[x.user_id]||{},l=lm[x.id]||{n:0,yes:false};return `<article class="post-card"><div class="post-head"><a href="${pu(u)}" class="post-user">${avatar(u)}<span><b>${esc(u.display_name||'Learner')}</b><small>@${esc(u.username||'')}</small></span></a><time>${new Date(x.created_at).toLocaleDateString()}</time></div><p class="post-content">${esc(x.content)}</p>${x.game?`<div class="post-game">🎮 ${esc(x.game)}${x.result_id?' · Result shared':''}</div>`:''}<div class="post-actions"><button data-like="${x.id}" class="${l.yes?'liked':''}">♥ ${l.n}</button><button data-comment="${x.id}">💬 Comment</button><button data-share="${x.id}">↗ Share</button></div><div class="comments" id="comments-${x.id}" hidden></div></article>`}).join('');box.querySelectorAll('[data-like]').forEach(b=>b.onclick=async()=>{if(!window.popUser){location.href='index.html';return;}const id=+b.dataset.like,{data}=await P().from('post_likes').select('*').eq('post_id',id).eq('user_id',window.popUser.id).maybeSingle();if(data)await P().from('post_likes').delete().eq('post_id',id).eq('user_id',window.popUser.id);else await P().from('post_likes').insert({post_id:id,user_id:window.popUser.id});load();});box.querySelectorAll('[data-share]').forEach(b=>b.onclick=async()=>{const url=location.href.split('?')[0]+`?post=${b.dataset.share}`;try{if(navigator.share)await navigator.share({title:'PopMastery',url});else{await navigator.clipboard.writeText(url);b.textContent='Copied!';}await P().from('post_shares').insert({post_id:+b.dataset.share,user_id:window.popUser?.id||null});}catch(e){}});box.querySelectorAll('[data-comment]').forEach(b=>b.onclick=async()=>{const c=$(`comments-${b.dataset.comment}`);c.hidden=!c.hidden;if(c.hidden)return;const {data}=await P().from('post_comments').select('*').eq('post_id',+b.dataset.comment).order('created_at');const ps=await profiles((data||[]).map(x=>x.user_id));c.innerHTML=(data||[]).map(x=>`<div class="comment"><b>${esc(ps[x.user_id]?.display_name||'Learner')}</b><p>${esc(x.content)}</p></div>`).join('')+ (window.popUser?`<form class="comment-form"><input maxlength="500" placeholder="Write a comment…"><button>Post</button></form>`:'');c.querySelector('form')?.addEventListener('submit',async e=>{e.preventDefault();const i=e.target.querySelector('input'),v=i.value.trim();if(v){await P().from('post_comments').insert({post_id:+b.dataset.comment,user_id:window.popUser.id,content:v});i.value='';await loadCommentsAfterSubmit(c,+b.dataset.comment);}});});}
async function loadCommentsAfterSubmit(c,id){const {data}=await P().from('post_comments').select('*').eq('post_id',id).order('created_at');const ps=await profiles((data||[]).map(x=>x.user_id));const form=c.querySelector('.comment-form');c.innerHTML=(data||[]).map(x=>`<div class="comment"><b>${esc(ps[x.user_id]?.display_name||'Learner')}</b><p>${esc(x.content)}</p></div>`).join('');if(form){c.appendChild(form);form.querySelector('input').value='';}}
async function load(){
  await waitAuth();
  if(!P())return;
  const username=new URLSearchParams(location.search).get('u');
  target=username?(await P().from('public_profiles').select('*').eq('username',username).maybeSingle()).data:await window.popEnsureSocialProfile();
  if(!target){$('profileHero').innerHTML='<div class="empty-card"><b>Profile not found</b><span>Sign in to create your learner profile.</span></div>';updateAuthButton();return;}
  updateAuthButton();
  const own=window.popUser?.id===target.id;
  const [{count:followers},{count:following},{data:rows}]=await Promise.all([P().from('follows').select('*',{count:'exact',head:true}).eq('following_id',target.id),P().from('follows').select('*',{count:'exact',head:true}).eq('follower_id',target.id),P().from('posts').select('*').eq('user_id',target.id).order('created_at',{ascending:false}).limit(40)]);
  let followingMe=false;if(window.popUser&&!own){const {data}=await P().from('follows').select('*').eq('follower_id',window.popUser.id).eq('following_id',target.id).maybeSingle();followingMe=!!data;}
  $('profileHero').innerHTML=`<div class="cover" ${target.cover_url?`style="background-image:url('${esc(target.cover_url)}')"`:''}></div><div class="profile-main"><div class="big-avatar">${avatar(target)}</div><div class="profile-info"><h1>${esc(target.display_name)}</h1><div class="handle">@${esc(target.username)}</div><p>${esc(target.bio||'Learning, playing and improving on PopMastery.')}</p><div class="profile-meta">${target.location?`<span>📍 ${esc(target.location)}</span>`:''}${target.website?`<a target="_blank" rel="noopener" href="${esc(target.website)}">🔗 Website</a>`:''}</div></div><div class="profile-actions">${own?'<button id="editBtn" class="outline-btn">Edit profile</button>':window.popUser?`<button id="followBtn" class="primary-btn">${followingMe?'Following':'Follow'}</button>`:`<button id="loginToFollow" class="primary-btn">Sign in to follow</button>`}<button id="shareProfile" class="outline-btn">↗ Share</button></div></div><div class="profile-stats"><b>${followers||0}<span>Followers</span></b><b>${following||0}<span>Following</span></b><b>${rows?.length||0}<span>Posts</span></b></div>`;
  await posts($('posts'),rows||[]);
  $('loginToFollow')?.addEventListener('click',()=>location.href='index.html');
  $('followBtn')?.addEventListener('click',async()=>{if(followingMe)await P().from('follows').delete().eq('follower_id',window.popUser.id).eq('following_id',target.id);else await P().from('follows').insert({follower_id:window.popUser.id,following_id:target.id});load();});
  $('shareProfile')?.addEventListener('click',async()=>{try{if(navigator.share)await navigator.share({title:`${target.display_name} on PopMastery`,url:location.href});else{await navigator.clipboard.writeText(location.href);$('shareProfile').textContent='Copied!';}}catch(e){}});
}
function updateAuthButton(){const b=$('authBtn');if(!b)return;if(window.popUser){b.textContent='My profile';b.onclick=()=>location.href='profile.html';}else{b.textContent='Sign in';b.onclick=()=>location.href='index.html';}}
async function save(){const patch={display_name:$('editName').value.trim()||'Learner',username:$('editUsername').value.trim().toLowerCase(),bio:$('editBio').value.trim(),location:$('editLocation').value.trim()||null,website:$('editWebsite').value.trim()||null,avatar_url:$('editAvatar').value.trim()||null,cover_url:$('editCover').value.trim()||null,updated_at:new Date().toISOString()};const {error}=await P().from('public_profiles').update(patch).eq('id',window.popUser.id);if(error){$('editMsg').textContent=error.message;return;}location.href=`profile.html?u=${encodeURIComponent(patch.username)}`;}
$('saveEdit')?.addEventListener('click',save);$('closeEdit')?.addEventListener('click',()=>$('editModal').classList.remove('open'));if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',load,{once:true});else load();
})();
