/* PopMastery social layer: feed, profiles, follows, likes, comments and shares. */
(function(){
  const $=id=>document.getElementById(id), POP=()=>window.popSupabase;
  const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
  const avatar=(p,size='sm')=>p?.avatar_url?`<img class="avatar-img ${size}" src="${esc(p.avatar_url)}" alt="">`:`<span class="avatar ${size}">${esc((p?.display_name||'L').charAt(0).toUpperCase())}</span>`;
  const profileUrl=p=>`profile.html?u=${encodeURIComponent(p.username)}`;
  async function requireAuth(){if(window.popUser)return true; alert('Sign in first to use this feature.'); document.dispatchEvent(new CustomEvent('open-pop-auth')); return false;}
  async function getProfiles(ids){if(!ids.length)return{};const {data}=await POP().from('public_profiles').select('id,username,display_name,avatar_url,bio').in('id',[...new Set(ids)]);return Object.fromEntries((data||[]).map(x=>[x.id,x]));}
  async function counts(postIds){if(!postIds.length)return{};const {data}=await POP().from('post_likes').select('post_id,user_id').in('post_id',postIds);const out={};(data||[]).forEach(x=>{out[x.post_id]??={likes:0,liked:false};out[x.post_id].likes++;if(x.user_id===window.popUser?.id)out[x.post_id].liked=true;});return out;}
  async function renderPosts(container,posts,options={}){
    if(!posts.length){container.innerHTML='<div class="empty-card"><b>No posts yet</b><span>Play a game and share your progress with the community.</span></div>';return;}
    const prof=await getProfiles(posts.map(p=>p.user_id)), cs=await counts(posts.map(p=>p.id));
    container.innerHTML=posts.map(p=>{const u=prof[p.user_id]||{display_name:'Learner',username:''},c=cs[p.id]||{likes:0,liked:false};return `<article class="post-card" data-post="${p.id}"><div class="post-head"><a href="${profileUrl(u)}" class="post-user">${avatar(u)}<span><b>${esc(u.display_name)}</b><small>@${esc(u.username)}</small></span></a><time>${new Date(p.created_at).toLocaleDateString(undefined,{month:'short',day:'numeric'})}</time></div><p class="post-content">${esc(p.content)}</p>${p.game?`<div class="post-game">🎮 ${esc(p.game)}${p.result_id?' · Result shared':''}</div>`:''}<div class="post-actions"><button class="like-btn ${c.liked?'liked':''}" data-action="like">♥ <span>${c.likes}</span></button><button data-action="comments">💬 Comment</button><button data-action="share">↗ Share</button></div><div class="comments" hidden><div class="comment-list"></div>${window.popUser?`<form class="comment-form"><input maxlength="500" placeholder="Write a comment…"><button>Post</button></form>`:'<small>Sign in to comment.</small>'}</div></article>`}).join('');
    container.querySelectorAll('.post-card').forEach(card=>bindPost(card));
  }
  async function bindPost(card){
    const id=Number(card.dataset.post), comments=card.querySelector('.comments');
    card.querySelector('[data-action="like"]').onclick=async()=>{if(!await requireAuth())return;const {data}=await POP().from('post_likes').select('post_id').eq('post_id',id).eq('user_id',window.popUser.id).maybeSingle();if(data)await POP().from('post_likes').delete().eq('post_id',id).eq('user_id',window.popUser.id);else{await POP().from('post_likes').insert({post_id:id,user_id:window.popUser.id});await POP().from('notifications').insert({user_id:(await postOwner(id)),actor_id:window.popUser.id,type:'like',post_id:id});}loadFeed();};
    card.querySelector('[data-action="comments"]').onclick=async()=>{comments.hidden=!comments.hidden;if(!comments.hidden)await loadComments(id,comments.querySelector('.comment-list'));};
    card.querySelector('[data-action="share"]').onclick=async()=>{const url=`${location.origin}${location.pathname.replace(/[^/]+$/,'')}profile.html?post=${id}`;try{if(navigator.share)await navigator.share({title:'PopMastery post',text:'Check this PopMastery post',url});else await navigator.clipboard.writeText(url);await POP().from('post_shares').insert({post_id:id,user_id:window.popUser?.id||null});}catch(e){if(e.name!=='AbortError')console.warn(e);}};
    card.querySelector('.comment-form')?.addEventListener('submit',async e=>{e.preventDefault();if(!await requireAuth())return;const input=e.target.querySelector('input'),content=input.value.trim();if(!content)return;await POP().from('post_comments').insert({post_id:id,user_id:window.popUser.id,content});input.value='';await loadComments(id,comments.querySelector('.comment-list'));});
  }
  async function postOwner(id){const {data}=await POP().from('posts').select('user_id').eq('id',id).single();return data?.user_id;}
  async function loadComments(id,box){const {data}=await POP().from('post_comments').select('*').eq('post_id',id).order('created_at',{ascending:true});const prof=await getProfiles((data||[]).map(x=>x.user_id));box.innerHTML=(data||[]).map(c=>`<div class="comment"><a href="${profileUrl(prof[c.user_id]||{})">${avatar(prof[c.user_id])}</a><div><b>${esc(prof[c.user_id]?.display_name||'Learner')}</b><p>${esc(c.content)}</p></div></div>`).join('')||'<small class="muted">No comments yet.</small>';}
  async function loadFeed(){const box=$('feedList');if(!box||!POP())return;let q=POP().from('posts').select('*').order('created_at',{ascending:false}).limit(50);const {data,error}=await q;if(error){box.innerHTML=`<div class="empty-card">${esc(error.message)}</div>`;return;}await renderPosts(box,data||[]);}
  async function publish(){if(!await requireAuth())return;const input=$('postComposer');const content=input.value.trim();if(!content)return;const {data,error}=await POP().from('posts').insert({user_id:window.popUser.id,content}).select('*').single();if(error){$('composerMsg').textContent=error.message;return;}await POP().from('activity_events').insert({user_id:window.popUser.id,event_type:'post_created',payload:{post_id:data.id}});input.value='';$('composerMsg').textContent='Posted!';loadFeed();}
  async function discover(){const box=$('discoverList');if(!box||!POP())return;const {data}=await POP().from('public_profiles').select('id,username,display_name,avatar_url,bio').eq('is_public',true).limit(12);const ids=(data||[]).map(x=>x.id);let following=new Set();if(window.popUser){const {data:f}=await POP().from('follows').select('following_id').eq('follower_id',window.popUser.id);following=new Set((f||[]).map(x=>x.following_id));}box.innerHTML=(data||[]).filter(p=>p.id!==window.popUser?.id).map(p=>`<div class="person-card">${avatar(p,'md')}<div><a href="${profileUrl(p)}"><b>${esc(p.display_name)}</b></a><small>@${esc(p.username)}</small><p>${esc(p.bio||'PopMastery learner')}</p></div><button class="follow-btn ${following.has(p.id)?'following':''}" data-id="${p.id}">${following.has(p.id)?'Following':'Follow'}</button></div>`).join('')||'<span class="muted">No learners to discover yet.</span>';
    box.querySelectorAll('.follow-btn').forEach(btn=>btn.onclick=async()=>{if(!await requireAuth())return;const target=btn.dataset.id;if(btn.classList.contains('following'))await POP().from('follows').delete().eq('follower_id',window.popUser.id).eq('following_id',target);else await POP().from('follows').insert({follower_id:window.popUser.id,following_id:target});discover();});
  }
  async function initFeed(){await new Promise(r=>{if(window.popSupabase)r();else document.addEventListener('pop-auth-ready',r,{once:true});});$('composerForm')?.addEventListener('submit',e=>{e.preventDefault();publish();});$('openProfile')?.addEventListener('click',()=>location.href='profile.html');await loadFeed();await discover();}
  window.PopSocial={loadFeed,renderPosts,loadComments,getProfiles};
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',initFeed,{once:true});else initFeed();
})();
